### ISSUE TITLE
find the caller of a tested function

### ISSUE THREAD

**Issue by matrixise** [nedbat/coveragepy-bbmirror#29]
Hi all,
with coverage and the tests, we can know if we test a code or not.
now, I would like to know the callers of a tested function.

in this section: https://coverage.readthedocs.io/en/coverage-4.3.4/cmd.html#diagnostics I see there are the callers, but how can we get the callers ? any idea ?
```
def baz():
   print("hello")

def bar():
   baz()

def foo():
   bar()

def test_function_a(self):
    foo()

def test_function_b(self):
   baz()
```
the results should be
* `test_function_a` for the `bar` function
* `test_function_a` and `test_function_b` for `baz` 

thanks

**Comment by nedbat** [comment]
I think you are asking for what I call [Who Tests What](https://nedbatchelder.com/blog/201612/who_tests_what.html), right?

**Comment by matrixise** [comment]
hi @nedbat yep, it's this feature. I do confirm, this feature would be awesome.
