### ISSUE TITLE
Report file format description

### ISSUE THREAD

**Issue by pawamoy** [nedbat/coveragepy-bbmirror#41]
Hi :wave:! 

In the generated `.coverage` file, it is written that the file uses a private format:
`!coverage.py: This is a private format, don't read it directly!`.
Is there a public format that we can use then?

I was searching online for documentation about coverage reports format standards or specifications, and I was surprised not to find any. It seems everybody uses its own format and its own tools to generate HTML (or else) reports.

Could you add a section in the documentation explaining your result file format? A bit like [Istanbul's one](https://github.com/gotwarlost/istanbul/blob/master/coverage.json.md)?

**Comment by nedbat** [comment]
How do you feel about the XML report?  It's in Cobertura format.

**Comment by Pawamoy** [comment]
Well, XML always seemed a bit overpowered and complicated to me, I would prefer JSON, YAML or even CSV a lot better. Is there a way to write a formatter plugin that would allow us to output a JSON report instead of an HTML/XML one?
